<a href="https://colab.research.google.com/github/raphamatoss/DeepLearningWithPyTorch/blob/main/IntroductionToTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**INTRODUCTION TO TENSORS**

A tensor is basically a generalization of mathematical values. Everything can be a tensor, a scalar, a vector or a matrix. Any R^n matrix is also a tensor!

Pytorch tensor documentation: https://pytorch.org/docs/stable/tensors.html

We can create tensors with pytorch as it follows:

In [5]:
import torch

# all of the four variables above are examples of tensors!
scalar = torch.tensor(7);
vector = torch.tensor([2, 2, 2, 2])
matrix = torch.tensor([[1, 1], [2,2],[3, 3]])
tensor = torch.tensor([[[1,1], [2, 2], [1, 1], [2, 2]]])

print("Scalar tensor: ")
print(scalar)
print("\nVector tensor: ")
print(vector)
print("\nMatrix tensor: ")
print(matrix)
print("\nMulti-dimensional tensor: ")
print(tensor)

# a torch tensor may also be initialized with a numpy array
import numpy as np
matrix_2 = torch.tensor(np.array([[1, 1 ,1], [2, 2, 2]]))

print("\nTensor using a numpy array: ")
print(matrix_2)

Scalar tensor: 
tensor(7)

Vector tensor: 
tensor([2, 2, 2, 2])

Matrix tensor: 
tensor([[1, 1],
        [2, 2],
        [3, 3]])

Multi-dimensional tensor: 
tensor([[[1, 1],
         [2, 2],
         [1, 1],
         [2, 2]]])

Tensor using a numpy array: 
tensor([[1, 1, 1],
        [2, 2, 2]])


**Dimension/Rank**

Every tensor has a **dimension**(also called **rank**), which stands for the number of indexes it is required to acess its information.

A **scalar has dimension 0**, since it isn't required any indexes to describe its value.

A **vector has dimension 1**, since it is required 1 index to describe its value

A **matrix has dimension 2**, since it is required 2 indexes to describe its values.

And so on. On Pytorch we can get the dimension of a tensor using the `.ndim`.

In [13]:
scalar.ndim

0

In [12]:
vector.ndim

1

In [14]:
tensor.ndim

3

**Shape/Size**

Tensors also have a **shape**(also called size). The shape of a tensor is related to its dimension, it represents the length of each dimension

In [15]:
tensor = torch.tensor([[[1, 1],
                        [2, 2],
                        [1, 1],
                        [2, 2]]])
tensor.shape

torch.Size([1, 4, 2])

**Data type**

If we want to specify the data type of a tensor, we can define `torch.dtype` in the `torch.tensor()` constructor:

In [26]:
integer_tensor = torch.tensor([1, 1, 1], dtype=torch.int16)
print(integer_tensor)

# If we want to get the type of a tensor we can do as it follows:
integer_tensor.dtype

tensor([1, 1, 1], dtype=torch.int16)


torch.int16

Tensor datatypes is one of the 3 big erros we may run into with PyTorch and DP:
1. Tensors not in the right datatype
2. Tensors not in the right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor is the standart tensor datatype when creating
# tensors with PyTorch
float_32 = torch.zeros(dtype=None, # what datatype the tensor is
                       device=None, # what device the tensor is on(Nvidia cuda, Tpu)
                       requires_grad=False) # wheter or not to track gradients with this tensors operations

**Random Tensors**

Random tensors are important because many neural networks start with random weights and adjust them to better values along the training step.

We can create random tensors using `torch.rand().`

In [21]:
# We can create a tensor of a desired shape by specifing it
# in the constructor
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.6563, 0.2599, 0.3710, 0.6606],
         [0.1729, 0.3650, 0.9097, 0.0899],
         [0.2889, 0.4661, 0.3250, 0.9224]],

        [[0.5874, 0.8911, 0.4843, 0.8245],
         [0.1069, 0.1288, 0.8897, 0.1500],
         [0.3921, 0.5909, 0.7304, 0.3086]]])

In [20]:
random_tensor.ndim

3

**Zeros and ones**

In [22]:
# We can also create tensors filled with zeros or ones
zeros = torch.zeros(3, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [23]:
ones = torch.ones(3, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

**Range of tensors**

Using `torch.arange(start, end, step)` we can create a 1D tensor with values from a specified interval.

In [29]:
# we can define only the start and end parameters
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# besides the start and end parameters, we can also define the step
one_to_hundred = torch.arange(0, 101, 5)
one_to_hundred

tensor([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75,  80,  85,  90,  95, 100])

**Tensors Like**

`torch.zeros_like(input)`
`torch.ones_like(input)`
`torch.rand_like(input)`

All of these pytorch methods return a tensor of the same shape as the input tensor.

In [9]:
tensor = torch.rand(1, 2, 5)
tensor

tensor([[[0.0629, 0.2848, 0.6810, 0.4568, 0.5433],
         [0.6851, 0.9922, 0.0263, 0.3169, 0.3326]]])

In [36]:
zeros_like = torch.zeros_like(tensor)
zeros_like

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [11]:
ones_like = torch.ones_like(tensor)
ones_like

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [10]:
rand_like = torch.rand_like(tensor)
rand_like

tensor([[[0.6188, 0.8906, 0.4084, 0.9898, 0.4653],
         [0.4391, 0.8416, 0.8188, 0.4704, 0.6474]]])

**TENSOR OPERATIONS**
1. Addition/Subtraction
2. Multiplication/Division
3. Matrix multiplication

In [12]:
# addition
tensor = torch.tensor([1, 2, 3])
tensor + 100

tensor([101, 102, 103])

In [14]:
torch.add(tensor, 100)

tensor([101, 102, 103])

In [18]:
tensor.add(10)

tensor([11, 12, 13])

In [13]:
# multiplication
tensor * 2

tensor([2, 4, 6])

In [16]:
torch.mul(tensor, 2)

tensor([2, 4, 6])

In [19]:
tensor.mul(2)

tensor([2, 4, 6])