<a href="https://colab.research.google.com/github/raphamatoss/DeepLearningWithPyTorch/blob/main/IntroductionToTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**INTRODUCTION TO TENSORS**

A tensor is basically a generalization of mathematical values. Everything can be a tensor, a scalar, a vector or a matrix. Any R^n matrix is also a tensor!

Pytorch tensor documentation: https://pytorch.org/docs/stable/tensors.html

We can create tensors with pytorch as it follows:

In [ ]:
import torch

# all of the four variables above are examples of tensors!
scalar = torch.tensor(7);
vector = torch.tensor([2, 2, 2, 2])
matrix = torch.tensor([[1, 1], [2,2],[3, 3]])
tensor = torch.tensor([[[1,1], [2, 2], [1, 1], [2, 2]]])

print("Scalar tensor: ")
print(scalar)
print("\nVector tensor: ")
print(vector)
print("\nMatrix tensor: ")
print(matrix)
print("\nMulti-dimensional tensor: ")
print(tensor)

# a torch tensor may also be initialized with a numpy array
import numpy as np
matrix_2 = torch.tensor(np.array([[1, 1 ,1], [2, 2, 2]]))

print("\nTensor using a numpy array: ")
print(matrix_2)

Scalar tensor: 
tensor(7)

Vector tensor: 
tensor([2, 2, 2, 2])

Matrix tensor: 
tensor([[1, 1],
        [2, 2],
        [3, 3]])

Multi-dimensional tensor: 
tensor([[[1, 1],
         [2, 2],
         [1, 1],
         [2, 2]]])

Tensor using a numpy array: 
tensor([[1, 1, 1],
        [2, 2, 2]])


**Dimension/Rank**

Every tensor has a **dimension**(also called **rank**), which stands for the number of indexes it is required to acess its information.

A **scalar has dimension 0**, since it isn't required any indexes to describe its value.

A **vector has dimension 1**, since it is required 1 index to describe its value

A **matrix has dimension 2**, since it is required 2 indexes to describe its values.

And so on. On Pytorch we can get the dimension of a tensor using the `.ndim`.

In [ ]:
scalar.ndim

0

In [ ]:
vector.ndim

1

In [ ]:
tensor.ndim

3

**Shape/Size**

Tensors also have a **shape**(also called size). The shape of a tensor is related to its dimension, it represents the length of each dimension

In [ ]:
tensor = torch.tensor([[[1, 1],
                        [2, 2],
                        [1, 1],
                        [2, 2]]])
tensor.shape

torch.Size([1, 4, 2])

**Data type**

If we want to specify the data type of a tensor, we can define `torch.dtype` in the `torch.tensor()` constructor:

In [ ]:
integer_tensor = torch.tensor([1, 1, 1], dtype=torch.int16)
print(integer_tensor)

# If we want to get the type of a tensor we can do as it follows:
integer_tensor.dtype

tensor([1, 1, 1], dtype=torch.int16)


torch.int16

Tensor datatypes is one of the 3 big erros we may run into with PyTorch and DP:
1. Tensors not in the right datatype
2. Tensors not in the right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor is the standart tensor datatype when creating
# tensors with PyTorch
float_32 = torch.zeros(dtype=None, # what datatype the tensor is
                       device=None, # what device the tensor is on(Nvidia cuda, Tpu)
                       requires_grad=False) # wheter or not to track gradients with this tensors operations

TypeError: zeros() received an invalid combination of arguments - got (requires_grad=bool, device=NoneType, dtype=NoneType, ), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (tuple of ints size, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)


**Random Tensors**

Random tensors are important because many neural networks start with random weights and adjust them to better values along the training step.

We can create random tensors using `torch.rand().`

In [ ]:
# We can create a tensor of a desired shape by specifing it
# in the constructor
random_tensor = torch.rand(2, 3, 4)
random_tensor

In [ ]:
random_tensor.ndim

**Zeros and ones**

In [ ]:
# We can also create tensors filled with zeros or ones
zeros = torch.zeros(3, 3)
zeros

In [ ]:
ones = torch.ones(3, 3)
ones

**Range of tensors**

Using `torch.arange(start, end, step)` we can create a 1D tensor with values from a specified interval.

In [ ]:
# we can define only the start and end parameters
one_to_ten = torch.arange(1, 11)
one_to_ten

In [ ]:
# besides the start and end parameters, we can also define the step
one_to_hundred = torch.arange(0, 101, 5)
one_to_hundred

**Tensors Like**

`torch.zeros_like(input)`
`torch.ones_like(input)`
`torch.rand_like(input)`

All of these pytorch methods return a tensor of the same shape as the input tensor.

In [ ]:
tensor = torch.rand(1, 2, 5)
tensor

In [ ]:
zeros_like = torch.zeros_like(tensor)
zeros_like

In [ ]:
ones_like = torch.ones_like(tensor)
ones_like

In [ ]:
rand_like = torch.rand_like(tensor)
rand_like

**TENSOR OPERATIONS**
1. Addition/Subtraction
2. Multiplication/Division
3. Matrix multiplication

In [ ]:
# addition
tensor = torch.tensor([1, 2, 3])
tensor + 100

In [ ]:
torch.add(tensor, 100)

In [ ]:
tensor.add(10)

In [ ]:
# multiplication
tensor * 2

In [ ]:
torch.mul(tensor, 2)

In [ ]:
tensor.mul(2)

**Matrix Multiplication**

Matrix multiplication uses the **dot product**, that means that to multiply a **m**x**n** matrix by a **n**x**p** matrix, the **n**s must be the same and it will result in a **m**x**p** matrix:
1. `(3, 2) @ (3, 2)` cannot be calculated
2. `(3, 2) @ (2, 3)` can be calculated -> `(3, 3)`
3. `(2, 3) @ (3, 2)` can be calculated -> `(2, 2)`

In [ ]:
torch.matmul(tensor, tensor)

In [ ]:
tensor_1 = torch.tensor([[2, 2, 2], [3, 3, 3]])
tensor_2 = torch.tensor([5, 5, 5])
torch.matmul(tensor_1, tensor_2)

If we want to multiply tensors of incompatible shapes, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.


In [ ]:
tensor_1 = torch.rand(3, 2)
tensor_2 = torch.rand(3, 2)
# the shape of the tensors above do not match, so if we try to run
# torch.mm(tensor_1, tensor_2) we will get an error, to fix this issue
# we can transpose one of our tensors:
tensor_1

In [ ]:
# by adding ".T" at the end, we get the transposed tensor
tensor_1.T

In [ ]:
# with that in mind, we can now multiply our tensors
torch.mm(tensor_1.T, tensor_2)

In [ ]:
print(f"Original shape: tensor_1 = {tensor_1.shape}, tensor_2 = {tensor_2.shape}")
print(f"Fixed shape: tensor_1 = {tensor_1.T.shape}, tensor_2 = {tensor_2.shape}")

**Min, max, mean and sum of a tensor**

In [ ]:
tensor = torch.arange(0, 101, 10)
tensor

In [ ]:
## min:
torch.min(tensor), tensor.min()

In [ ]:
## max:
torch.max(tensor), tensor.max()

In [ ]:
## mean:
tensor = tensor.type(torch.float32)
# the input tensor of the torch.mean must be a float or a complex
torch.mean(tensor), tensor.mean()

In [ ]:
## sum:
torch.sum(tensor), tensor.sum()

**Positional min and max of a tensor**

It is the index which holds the min/max value

In [ ]:
tensor

In [ ]:
# positional min = torch.argmin() -> returns the index of the min value within the tensor
torch.argmin(tensor), tensor.argmin()

In [ ]:
# positional max = torch.argmax() -> returns the index of the max value within the tensor
torch.argmax(tensor), tensor.argmax()

**Reshape, stack, squeeze and unsqueeze tensors**

**Reshape:** reshapes an input tensor to a defined shape, it is required that the new shape is compatible with the old one

**View:** returns a view of an input tensor of certain shape but shares the memory with input, that means changing the view will also affect the original input

**Stack:** concatenates a sequence of tensors along a new dimension. All tensors must be of the same size. There is a vstack for vertical stack and a hstack for horizontal stack.

**Squeeze:** removes all "1" dimensions from a tensor. The returned tensor shares the storage with the input tensor, so changing the contents of one will change the contentes of other.

**Unsqueeze:** adds a "1" dimension to a target tensor. The returned tensor also shares the storage with the input tensor.

**Permute:** returns a view of the input with dimensions permuted in a specified order


In [ ]:
import torch
## reshaping
tensor = torch.zeros(5)
tensor.shape

torch.Size([5])

In [ ]:
# it works since 1*5 = 5, which is the original shape
tensor.reshape(1, 5)

tensor([[0., 0., 0., 0., 0.]])

In [ ]:
# but if instead we try 2*5 = 10, it won't work, since 10 is double the size of the original
tensor.reshape(2, 5)

RuntimeError: shape '[2, 5]' is invalid for input of size 5

In [ ]:
## view
x = tensor.view(1, 5)
x[0][0] = 5 # changing the view will also change the original tensor
y = tensor.reshape(5) # since the original was changed, we'll notice the changes here
x, y

(tensor([[5., 5., 0., 0., 0.]]), tensor([5., 5., 0., 0., 0.]))

In [ ]:
## stacking tensors
tensor_a = torch.rand(5)
tensor_b = torch.rand(5)
stacked_tensor = torch.stack([tensor_a, tensor_b], dim=0)
tensor_a, tensor_b, stacked_tensor

(tensor([0.6602, 0.1583, 0.7621, 0.8695, 0.8574]),
 tensor([0.5930, 0.6247, 0.1203, 0.3678, 0.2650]),
 tensor([[0.6602, 0.1583, 0.7621, 0.8695, 0.8574],
         [0.5930, 0.6247, 0.1203, 0.3678, 0.2650]]))

In [ ]:
stacked_tensor = torch.stack([tensor_a, tensor_b], dim=1)
stacked_tensor

tensor([[0.6602, 0.5930],
        [0.1583, 0.6247],
        [0.7621, 0.1203],
        [0.8695, 0.3678],
        [0.8574, 0.2650]])

In [ ]:
## squeezing tensors
tensor = torch.zeros(2, 1, 2, 1, 2)
tensor.shape

torch.Size([2, 1, 2, 1, 2])

In [ ]:
x = torch.squeeze(tensor)
x.shape

torch.Size([2, 2, 2])

In [ ]:
# we can also select which dimension we want to squeeze
x = torch.squeeze(tensor, 1)
x.shape

torch.Size([2, 2, 1, 2])

In [ ]:
# since their storage are shared, if we change the content of one, both are affected
tensor[0][0][0][0][0] = 1
tensor, x

(tensor([[[[[1., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 tensor([[[1., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]))

In [ ]:
## unsqueezing tensors
tensor = torch.zeros(2, 2)

unsqueezed_tensor = torch.unsqueeze(tensor, 0)
tensor.shape, unsqueezed_tensor.shape

(torch.Size([2, 2]), torch.Size([1, 2, 2]))

In [ ]:
## permuting tensor's dimensions
tensor = torch.rand(224, 224, 3) #[height, width, colour_channels]

tensor_permuted = torch.permute(tensor, (2, 0, 1)) #[colour_channels, height, width]
tensor.shape, tensor_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

**Indexing tensors(selecting data)**

In [ ]:
tensor = torch.zeros(1, 2, 2)
tensor

tensor([[[0., 0.],
         [0., 0.]]])

In [ ]:
tensor[0]

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
tensor[0][0], tensor[0, 0]

(tensor([0., 0.]), tensor([0., 0.]))

In [ ]:
tensor[0][0][0], tensor[0, 0, 0]

(tensor(0.), tensor(0.))

In [ ]:
# we can also use ":" to select "all" of a target dimension
tensor[0, 0, :]

tensor([0., 0.])

In [ ]:
tensor[:, :, :]

tensor([[[0., 0.],
         [0., 0.]]])

In [ ]:
tensor[:, 1, 1]

tensor([0.])

**NumPy and PyTorch**

PyTorch accepts data from numPy as input

`torch.from_numpy(np_array)`

`torch.Tensor.numpy()`

In [ ]:
import torch
import numpy as np

# NumPy to tensor
array = np.arange(1, 8)
tensor = torch.from_numpy(array) # note that converting a numpy array to a tensor keeps the same data type
array.dtype, tensor.dtype

(dtype('int64'), torch.int64)

In [ ]:
# tensor to NumPy
tensor = torch.ones(5)
numpy_array = tensor.numpy()
tensor, numpy_array

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

**Reproducibility(making random inputs reproducible)**

https://pytorch.org/docs/stable/notes/randomness.html

In [2]:
import torch

# if we set a seed we can reproduce the generation of random numbers
torch.manual_seed(4)
random_tensor_1 = torch.rand(2, 2)
random_tensor_2 = torch.rand(2, 2)

print(random_tensor_1)
print(random_tensor_2)
print(random_tensor_1 == random_tensor_2)

tensor([[0.5596, 0.5591],
        [0.0915, 0.2100]])
tensor([[0.0072, 0.0390],
        [0.9929, 0.9131]])
tensor([[False, False],
        [False, False]])


In [4]:
# so if we reuse the seed, we will end up getting the same random numbers
# and reproducing our randomness
torch.manual_seed(4)
random_tensor_3 = torch.rand(2, 2)
random_tensor_4 = torch.rand(2, 2)

print(random_tensor_3)
print(random_tensor_4)
print(random_tensor_1 == random_tensor_3)
print(random_tensor_2 == random_tensor_4)

tensor([[0.5596, 0.5591],
        [0.0915, 0.2100]])
tensor([[0.0072, 0.0390],
        [0.9929, 0.9131]])
tensor([[True, True],
        [True, True]])
tensor([[True, True],
        [True, True]])


**Setting up a gpu in PyTorch**

https://pytorch.org/tutorials/recipes/recipes/changing_default_device.html

**Putting tensors(and models) in a gpu**

In [1]:
import torch
# When we create a tensor, it's by default on the CPU
tensor = torch.tensor([1, 2, 3])
tensor.device

device(type='cpu')

In [5]:
# We need to move the tensor to a gpu for faster computation
tensor = tensor.to(device="cuda")
tensor.device

device(type='cuda', index=0)

In [17]:
# to set all of tensors by default on gpu we may run:
torch.set_default_device('cuda')

tensor = torch.tensor([1, 2, 3])
tensor_2 = torch.rand(1, 2)
tensor.device, tensor_2.device

(device(type='cuda', index=0), device(type='cuda', index=0))

NumPy does not accept data on the GPU, so if we need to use NumPy we first need to get the tensor back to the CPU with:
`Tensor.cpu()`

In [18]:
tensor = tensor.cpu()
tensor.device

device(type='cpu')